### ISSUE TITLE
Add background image 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Soumyajit2825/TO-DO-LIST#19] opened 2022-10-09 09:21 UTC

**Comment by AnshuPathak-88825** [comment] 2022-10-09 09:22
pls assign me this issue @Soumyajit2825

**Comment by Soumyajit2825** [comment] 2022-10-09 09:30
Add a relevant back-ground image which is both visible clearly in dark and light mode

**Comment by ShishuSidharth** [comment] 2022-10-09 09:31
Hey is it available  then please assign this to me

**Comment by Soumyajit2825** [comment] 2022-10-09 09:32
Sorry but someone is already assigned on it. Search some other issues related with this to-do-list
You can create your own issue

**Comment by Soumyajit2825** [comment] 2022-10-10 13:17
@AnshuPathak-88825 have u got the bg-image of the project???or still working on it

**Comment by AnshuPathak-88825** [comment] 2022-10-10 14:56
I'm unable to find relevant  background image 

https://user-images.githubusercontent.com/78332454/194893967-78117a3e-3139-415b-aa12-ab09f3b18b20.mp4

How about it is it UI  looking good ? pls let me know @Soumyajit2825 
then I'll working on it

**Comment by Soumyajit2825** [comment] 2022-10-10 15:03
It's a not a background image right
JUst a style

**Comment by AnshuPathak-88825** [comment] 2022-10-10 15:09
I'm not able to find relevant image so  you can assign it to someone else

**Comment by ShishuSidharth** [comment] 2022-10-11 07:09
Thanks @Soumyajit2825  i will definitely work on it

**Comment by snehadrita** [comment] 2022-10-12 05:19
assign me this

**Comment by Soumyajit2825** [comment] 2022-10-12 09:13
@snehadrita yeh budyy

**Comment by jyotika6221** [comment] 2022-10-15 19:49
Hey if the issue is open, plz assign it to me.

**Comment by Soumyajit2825** [comment] 2022-10-16 12:13
@jyotika6221 go fot it

**Closed** 2022-10-26 12:10 UTC
Labels: hacktoberfest, hacktoberfest-accepted, beginner-friendly
